config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :developers

  resources :admins

  resources :stories

  resources :projects

  get 'projects/:id/newstory' => 'projects#newstory', as: :newstory
  get 'admins/:id/showstories' => 'admins#showstories', as: :showstories
  get 'admins/:id/destroyprojects' => 'admins#destroyprojects', as: :destroyprojects
  get 'developers/:id/createstory' => 'developers#createstory', as: :createstory
  get 'developers/:id/signup' => 'developers#signup', as: :signup
  get 'developers/:id/passwordchange' => 'developers#passwordchange', as: :passwordchange

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  get  'logout' =>'sessions#logout'
  root 'sessions#create'
  get 'search' =>'projects#search'

end

app/models/developer.rb
class Developer < ActiveRecord::Base
  belongs_to :Project
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:signup,:show, :edit, :update, :destroy, :passwordchange]

  # GET /developers
  # GET /developers.json
  def index
    @developers = Developer.all
    @project = Project.all
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
 #   @developer =Developer.all
    @project = Project.all
    @stories = Story.all.select{|s| s.Developer_id == @developer.id}
    @allstories = Story.all.select{|s| s.Project_id == @developer.Project_id}
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers
  # POST /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  def createstory
    @story = Story.new
    #Story.new.Developer_id = params[:id]
    @developer = Developer.find(params[:id])
    @projects = Project.all
    @projects.each do |f|
      @protitle = f.title if (f.id == @developer.Project_id )
    end
  end

  def signup
    @stories = Story.all.select{|s| s.Project_id == @developer.Project_id}
  end

  # PATCH/PUT /developers/1
  # PATCH/PUT /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Developer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   def passwordchange

   end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def developer_params
      params.require(:developer).permit(:name, :email, :password, :Project_id, :Story_id)
    end
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_form.html.erb
<%= form_for(@developer) do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% @developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :Project_id %><br>
    <%= select(:developer, :Project_id, Project.all.collect{ |c| [c.title,c.id]}) %>
    <!--<%= f.text_field :Project_id %> -->
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/developers/createstory.html.erb
<%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

          <ul>
            <% @story.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <br>
    <div class="field">
      <%= f.label "Story Creater" %><br>
      <%= select(:story, :Developer_id, [[@developer.name,@developer.id]]) %>
    </div>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :Project %><br>
      <%= select(:story, :Project_id, [[@protitle,@developer.Project_id]]) %>
    </div>
    <div class="field">
      <%= f.label :point_value %><br>
      <%= f.number_field :point_value %>
    </div>
    <div class="field">
      <%= f.label :Stage %><br>
      <!--<%= f.text_field :Stage %>-->
      <%= select("story", "Stage", ['Analysis','Ready For Dev','In Dev','Dev Complete','In Test','Complete'].collect{ |c| c}) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing Developer</h1>

<%= render 'form' %>

<%= link_to 'Show', @developer %> |
<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Developers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.name %></td>
        <td><%= developer.email %></td>
        <td><%= developer.password %></td>
        <td><% @project.each do |f| %>
            <%= f.title if (f.id == developer.Project_id ) %>
        <% end %></td>
        <td><%= link_to 'Show', developer %></td>
        <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New Developer</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/developers/passwordchange.html.erb
<%= form_for(@developer) do |f| %>
    <% if @developer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this admin from being saved:</h2>

          <ul>
            <% @developer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<%end%>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @developer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @developer.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @developer.password %>
</p>

<p>
  <strong>Project:</strong>
  <% @project.each do |f| %>
  <%= f.title if (f.id == @developer.Project_id ) %>
  <% end %>
</p>
<br>
<%= link_to "Log out", logout_path %><br>
<%= link_to "change your password", passwordchange_path %><br>
<h1>Listing All Stories</h1>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Point value</th>
    <th>Stage</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @allstories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= story.point_value %></td>
        <td><%= story.Stage %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><% end %></td>
  </tr>
  </tbody>
</table>

<h1>Listing Stories created by you</h1>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Point value</th>
    <th>Stage</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
<% @stories.each do |story| %>
    <tr>
      <td><%= story.title %></td>
      <td><%= story.description %></td>
      <td><%= story.point_value %></td>
      <td><%= story.Stage %></td>
      <td><%= link_to 'Show', story %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link_to 'create a story', createstory_path %> <br> <br>
<%= link_to 'sign up a story', signup_path %> <br> <br>
<%= link_to 'Back', admins_path %>

app/views/developers/signup.html.erb
<%= form_for(@developer) do |f| %>
    <% if @developer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this story from being saved:</h2>

          <ul>
            <% @developer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label "Sign up a story" %><br>
      <%= select("developer", "Story_id", @stories.collect{ |c| [c.title,c.id]}) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>