config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :developers

  resources :admins

  resources :stories

  resources :projects

  get 'projects/:id/newstory' => 'projects#newstory', as: :newstory
  get 'admins/:id/showstories' => 'admins#showstories', as: :showstories
  get 'admins/:id/destroyprojects' => 'admins#destroyprojects', as: :destroyprojects
  get 'developers/:id/createstory' => 'developers#createstory', as: :createstory
  get 'developers/:id/signup' => 'developers#signup', as: :signup
  get 'developers/:id/passwordchange' => 'developers#passwordchange', as: :passwordchange

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  get  'logout' =>'sessions#logout'
  root 'sessions#create'
  get 'search' =>'projects#search'

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.password %></td>
        <td><%= link_to 'Show', admin %></td>
       <!-- <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

<h1>Listing Projects</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Developer</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.developer %></td>
        <td><%= link_to 'Show all stories', showstories_path(project) %></td>
      <!--  <td><%= link_to 'Edit', edit_project_path(project) %></td>-->
        <td><%= link_to 'Destroy', destroyprojects_path(project), data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New project', new_project_path %>

<h1>Listing Developers</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Project</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.name %></td>
        <td><%= developer.email %></td>
        <td><%= developer.password %></td>
        <td><% @projects.each do |f| %>
              <%= f.title if (f.id == developer.Project_id ) %>
          <% end %></td>
        <td><%= link_to 'Show', developer %></td>
        <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Developer', new_developer_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>
aaaaa
<%= link_to "Log out", logout_path %><br>
<h1>Listing Admins</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.password %></td>
        <td><%= link_to 'Show', admin %></td>
        <!-- <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

<h1>Listing Projects</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Developer</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.developer %></td>
        <td><%= link_to 'Show all stories', showstories_path(project) %></td>
        <!--  <td><%= link_to 'Edit', edit_project_path(project) %></td>-->
        <td><%= link_to 'Destroy', destroyprojects_path(project), data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New project', new_project_path %>

<h1>Listing Developers</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Project</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.name %></td>
        <td><%= developer.email %></td>
        <td><%= developer.password %></td>
        <td><% @projects.each do |f| %>
              <%= f.title if (f.id == developer.Project_id ) %>
          <% end %></td>
        <td><%= link_to 'Show', developer %></td>
        <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Developer', new_developer_path %>
<br>
<br>
<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>
<%= link_to 'New Project', projects_path %>

app/views/admins/showstories.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @project.developer %>
</p>

<tbody>
<p>
  <strong>All stories:</strong>
  <% @stories.each do |story| %>
      <tr>
        <td><%= story.title if story.Project_id == @project.id %></td>
      </tr>
  <% end %>
</p>
</tbody>

<tbody>
<p>
  <strong>Storyboard:</strong><br>
  Stories that are not Completed:
  <% @stories.each do |story| %>
      <tr>
        <td><%= story.title if (story.Project_id == @project.id && story.Stage != 'Complete') %></td>
      </tr>
  <% end %>
  <br>
  Points for each Stage:<br>
  Analysis: <%=@t0 %><br>
  Ready For Dev: <%=@t1 %><br>
  In Dev: <%=@t2 %><br>
  Dev Complete: <%=@t3 %><br>
  In Test: <%=@t4 %><br>
  Complete: <%=@t5 %><br>

</p>
</tbody>


<%= link_to 'Back', admins_path %>