config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :developers

  resources :admins

  resources :stories

  resources :projects

  get 'projects/:id/newstory' => 'projects#newstory', as: :newstory
  get 'admins/:id/showstories' => 'admins#showstories', as: :showstories
  get 'admins/:id/destroyprojects' => 'admins#destroyprojects', as: :destroyprojects
  get 'developers/:id/createstory' => 'developers#createstory', as: :createstory
  get 'developers/:id/signup' => 'developers#signup', as: :signup
  get 'developers/:id/passwordchange' => 'developers#passwordchange', as: :passwordchange

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  get  'logout' =>'sessions#logout'
  root 'sessions#create'
  get 'search' =>'projects#search'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :stories

  validates :title, :presence => true
  validates :description, :presence => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @t0=0
    @t1=0
    @t2=0
    @t3=0
    @t4=0
    @t5=0
    @stories = Story.all
    Story.all.each{|s| @t0+=s.point_value if (s.Stage == 'Analysis' && s.Project_id == @project.id)}
    Story.all.each{|s| @t1+=s.point_value if (s.Stage == 'Ready For Dev' && s.Project_id == @project.id)}
    Story.all.each{|s| @t2+=s.point_value if (s.Stage == 'In Dev' && s.Project_id == @project.id)}
    Story.all.each{|s| @t3+=s.point_value if (s.Stage == 'Dev Complete' && s.Project_id == @project.id)}
    Story.all.each{|s| @t4+=s.point_value if (s.Stage == 'In Test' && s.Project_id == @project.id)}
    Story.all.each{|s| @t5+=s.point_value if (s.Stage == 'Complete' && s.Project_id == @project.id)}
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def newstory
    @story = Story.new
    @project = Project.find(params[:id])
  end

  def search
    @project = Project.find(params[:parent_id])
    @stories = Story.all.select { |story| ((story.title =~ /#{params[:q]}/i) ||(story.description =~ /#{params[:q]}/i) ) && (story.Project_id == @project.id)}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :developer)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :developer %><br>
    <%= f.text_field :developer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Developer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.developer %></td>
        <td><%= link_to 'Show all stories', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/newstory.html.erb
<%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

          <ul>
            <% @story.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :Project %><br>
      <%= select(:story, :Project_id, [[@project.title,@project.id]]) %>
     <!-- <%= select("story", "Project_id", [@project.title, @project.id]) %>-->
    </div>
    <div class="field">
      <%= f.label :point_value %><br>
      <%= f.number_field :point_value %>
    </div>
    <div class="field">
      <%= f.label :Stage %><br>
      <!--<%= f.text_field :Stage %>-->
      <%= select("story", "Stage", ['Analysis','Ready For Dev','In Dev','Dev Complete','In Test','Complete'].collect{ |c| c}) %>

    </div>
    <div class="field">
      <%= f.label :Developer %><br>
      <%= f.text_field :Developer %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--   stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' true  -->
  <!-- javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <!-- csrf_meta_tags %>-->
</head>

<body>

<% if @stories.empty? %>
    <h3><font color="red">No results found</font><br/></h3>
<% else %>
    <table>
      <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Point Value</th>
        <th>Stage</th>
        <th colspan="2">Options</th>
      </tr>
      </thead>

      <h3>Story search results</h3>
      <tbody>
      <% @stories.each do |story| %>
          <tr>
            <td><%= story.title %></td>
            <td><%= story.description%></td>
            <td><%= story.point_value%></td>
            <td><%= story.Stage%></td>
            <td><%= link_to 'Show', story %></td>
            <td><%= link_to 'Edit', edit_story_path(story) %></td>
          </tr>
      <% end %>
      </tbody>
<% end %>
</table>
</body>
</html>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @project.developer %>
</p>

<tbody>
<p>
  <strong>All stories:</strong>
  <% @stories.each do |story| %>
      <tr>
        <td><%= story.title if story.Project_id == @project.id %></td>
      </tr>
  <% end %>
</p>
</tbody>

<%= form_tag("/search", method: "get") do %>
    <%= text_field_tag(:q) %>
    <%= hidden_field_tag(:parent_id, @project.id)%>
    <%= submit_tag('Search Stories') %>
<% end %>
<br/>

<tbody>
<p>
  <strong>Storyboard:</strong><br>
  Stories that are not Completed:
  <% @stories.each do |story| %>
      <tr>
        <td><%= story.title if (story.Project_id == @project.id && story.Stage != 'Complete') %></td>
      </tr>
  <% end %>
  <br>
  Points for each Stage:<br>
  Analysis: <%=@t0 %><br>
  Ready For Dev: <%=@t1 %><br>
  In Dev: <%=@t2 %><br>
  Dev Complete: <%=@t3 %><br>
  In Test: <%=@t4 %><br>
  Complete: <%=@t5 %><br>

</p>
</tbody>


<%= link_to 'New Story', newstory_path%> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>