config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :developers

  resources :admins

  resources :stories

  resources :projects

  get 'projects/:id/newstory' => 'projects#newstory', as: :newstory
  get 'admins/:id/showstories' => 'admins#showstories', as: :showstories
  get 'admins/:id/destroyprojects' => 'admins#destroyprojects', as: :destroyprojects
  get 'developers/:id/createstory' => 'developers#createstory', as: :createstory
  get 'developers/:id/signup' => 'developers#signup', as: :signup
  get 'developers/:id/passwordchange' => 'developers#passwordchange', as: :passwordchange

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  get  'logout' =>'sessions#logout'
  root 'sessions#create'
  get 'search' =>'projects#search'

end

app/models/story.rb
class Story < ActiveRecord::Base
  include Enumerable
  belongs_to :project

  validates :title, :presence => true
  validates :description, :presence => true
  validates :point_value, :presence => true
  validates :Stage, :presence => true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    #@project = Project.find(params[:Project_id])
    #@story = @project.stories.create(story_params)
    #redirect_to project_path(@project)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:Developer_id, :title, :description, :point_value, :Stage, :Developer, :Project_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    <div class="field">
      <%= f.label :Project %><br>
     <%= select("story", "Project_id", Project.all.collect{ |c| [c.title, c.id]}) %>
    </div>
  <div class="field">
    <%= f.label :point_value %><br>
    <%= f.number_field :point_value %>
  </div>
  <div class="field">
    <%= f.label :Stage %><br>
    <!--<%= f.text_field :Stage %>-->
    <%= select("story", "Stage", ['Analysis','Ready For Dev','In Dev','Dev Complete','In Test','Complete'].collect{ |c| c}) %>

  </div>
  <div class="field">
    <%= f.label :Developer %><br>
    <%= f.text_field :Developer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Point value</th>
      <th>Stage</th>
      <th>Developer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.description %></td>
        <td><%= story.point_value %></td>
        <td><%= story.Stage %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><% end %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Point value:</strong>
  <%= @story.point_value %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @story.Stage %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @story.Developer %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>